version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

    environment:
      POSTGRES_DB: cloudstorage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cloudstorage
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123123
      SPRING_FLYWAY_URL: jdbc:postgresql://postgres:5432/cloudstorage
      SPRING_FLYWAY_USER: postgres
      SPRING_FLYWAY_PASSWORD: 123123

    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs

#volumes:
#  postgres_data:

# потом перенести в volumes докера